### ISSUE TITLE
Update to react 15

### ISSUE THREAD

**Issue by mladen107** [dkozar/react-data-menu#1]
Hello and good job with library so far!
Are there any plans to update this to work with react 15._._ ?

**Comment by dkozar** [comment]
Sure, with time.

You could temporarily fork it if in need.

**Comment by alanzhaonys** [comment]
Do you have a time frame for the react 15 changes? thanks

**Comment by dkozar** [comment]
I'll have a timeframe by the end of next week (sorry too bussy and got cold on top). This clearly needs to be done.

I'll move 0.14 into branch, so no worries for 0.14 users.

**Comment by alanzhaonys** [comment]
Awesome! I'll wait. Hope you feel better soon. Thank you!

**Comment by dkozar** [comment]
Done: https://github.com/dkozar/react-data-menu/commit/ab40bc3d2a754f4d1c1a0cba7fefda0064d8d250

The react-0.14 version copied to the maintenance branch: https://github.com/dkozar/react-data-menu/commits/react-0.14
