### ISSUE TITLE
Compile on case sensitive systems

### ISSUE THREAD

**Issue by jonathannaim** [dkozar/react-data-menu#3]
Love the library! I'm building on a case sensitive system and some imports do not match the path exactly.

for ex, in MenuPopupFactory.js
`import Dom from './../util/Dom';`

should be 

`import Dom from './../util/dom';`

I can do a PR if you want?

**Comment by dkozar** [comment]
Sure, my friend. Go ahead!

I prefer the file to be renamed to "Dom.js".

Thanks for spotting the error,

Danko

**Comment by dkozar** [comment]
Merged. Thanks! =)

**Comment by jonathannaim** [comment]
Anytime! 
Any chance you could you publish the new version on npm?

**Comment by dkozar** [comment]
Sorry, I forgot. Published!

**Comment by jonathannaim** [comment]
You are a rockstar! Thanks VM!!
